import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ClientWrapper from './ClientWrapper'
import LoginPage from './home/login'
import Dashboard from './home/dashboard'
import ListaCompras from './home/lista'
import RegisterPage from './home/cadastro'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper><ListaCompras/></ClientWrapper>
      </body>
    </html>
  )
}
